version: 2
jobs:
   build:
   steps:
       machine:
         services:
           - docker

       dependencies:
         override:
           - docker info
           - docker build --rm=false -t circleci/elasticsearch .
