version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t orangewhale .
 test1:
   machine: true
   steps:
     - checkout
     - test:
      name: test application
        - checkout
        - run: docker build -t orangewhale .
        - run: docker run orangewhale:latest
 deploy:
   machine: true
   steps:
     - checkout
     - deploy:
        name: Push application Docker image to ecs
        - checkout
        - run: docker build -t orangewhale .
        command: |
          sh ./deploy.sh
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - deploy:
          requires:
            - test1
