version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t orangewhale .
     - deploy:
         name: Push application Docker image
         command: |
         sh ./deploy.sh
